### ISSUE TITLE
CL Provider breaks

### ISSUE THREAD

**Issue by salinaaaaaa** [koopjs/koop-app-example#68]
```
{"level":"info","message":"registered provider: craigslist 2.0.1"}
(node:2640) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at Function.listen (C:\Users\janes\Desktop\koop-app-example\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\janes\Desktop\koop-app-example\src\index.js:22:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1512:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8080
}

Node.js v18.12.1
```

**Comment by rgwozdz** [comment]
It looks like you are trying to start the koop webserver with port 8080 and it is already in use on your machine.

**Comment by salinaaaaaa** [comment]
Yup, its fixed :) 
Thanks!!!
